//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.Iservice1")]
    public interface Iservice1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iservice1/Hello", ReplyAction="http://tempuri.org/Iservice1/HelloResponse")]
        string Hello(string x);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Iservice1Channel : MyClient.ServiceReference1.Iservice1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Iservice1Client : System.ServiceModel.ClientBase<MyClient.ServiceReference1.Iservice1>, MyClient.ServiceReference1.Iservice1 {
        
        public Iservice1Client() {
        }
        
        public Iservice1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Iservice1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Iservice1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Iservice1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Hello(string x) {
            return base.Channel.Hello(x);
        }
    }
}
